"""Embed the approved PCM WAVs verbatim. No runtime filesystem or decoder dependency."""
from pathlib import Path
import hashlib
import wave

root = Path(__file__).resolve().parents[1]
lines = ['// Generated by scripts/embed_success_audio.py; do not edit the bytes.',
         '#include "success_audio_data.h"', 'namespace codexpet {']
for name, filename in [('kSuccessVoiceWav', 'tada-voice.wav'), ('kSuccessFanfareWav', 'tada-two-notes.wav')]:
    path = root / 'assets/audio' / filename
    with wave.open(str(path)) as audio:
        assert audio.getnchannels() == 1 and audio.getsampwidth() == 2
        assert audio.getnframes() / audio.getframerate() < 2
    data = path.read_bytes()
    lines += ['// SHA-256: ' + hashlib.sha256(data).hexdigest(), f'alignas(4) const uint8_t {name}[] = {{']
    lines += ['  ' + ','.join(f'0x{x:02x}' for x in data[i:i+24]) + ',' for i in range(0,len(data),24)]
    lines += ['};', f'const size_t {name}Size = sizeof({name});']
lines += ['} // namespace codexpet', '']
(root/'src/success_audio_data.cpp').write_text('\n'.join(lines), encoding='utf-8')
print('Embedded approved voice and two-note cue without audio modification.')
